# Add script to Workflow
# You can execute bash scripts within a Github Actions workflow
name: Run Bash script

on: workflow_dispatch

jobs:
  example-job:
    runs-on: ubuntu-latest
    defaults:
      - run:
          working-directory: ./scripts
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Run a script
        run: ./my-script.sh
      - name: Run another script
        run: ./my-other-script.sh