on: [push,workflow_dispatch]

jobs:
  my-job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: AllyannaRC/custom-action-example@0.0.5
        with:
          name: 'Brown'
      # Use the output from the `hello` step
      - name: Get the Output
        run: echo "The time was ${{ steps.hello.outputs.greeting }}"