name: Encrypted Secrets

on: [push]

jobs:
  use-secret-as-input:  # Passing Secrets as Inputs -  You can pass secrets as inputs by using the secrets context.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Custom Action using Secret
        uses: example/action@v1
        with:
          api-key: ${{ secrets.API_KEY }}

  use-secret-as-env: # Passing Secrets as Env Vars - You can also pass secrets to actions or scripts by setting them as environment variables
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a script using Secret
        run: |
          echo "Using API key: $API_KEY"
        env:
          API_KEY: ${{ secrets.API_KEY }}
