# Publish Docker Hub Registry using Workflow
name: Publish Docker Image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    - name: Push Docker image to Docker Hub
      runs-on: ubuntu-latest
      steps:
        - name: Check out to repo
          uses: actions/checkout@v4

        - name: Log in to Docker Hub
          uses: docker/login-action@1234
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metdata-actions@1234
          with:
            images: my-docker-hub-namespace/my-docker-hub-repository
        
        - name: Build and push Docker image
          uses: docker/build-push-action@1234
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}